package com.barrybecker4.mapland.backend.datastore;

import com.barrybecker4.mapland.backend.datamodel.GameBean;
import com.google.api.services.datastore.DatastoreV1;
import com.google.api.services.datastore.DatastoreV1.CommitRequest;
import com.google.api.services.datastore.DatastoreV1.Entity;
import com.google.api.services.datastore.DatastoreV1.Key;
import com.google.api.services.datastore.DatastoreV1.LookupRequest;
import com.google.api.services.datastore.DatastoreV1.LookupResponse;
import com.google.api.services.datastore.DatastoreV1.Property;
import com.google.api.services.datastore.DatastoreV1.Value;
import com.google.api.services.datastore.client.DatastoreException;
import com.google.protobuf.ByteString;
import com.google.api.services.datastore.DatastoreV1.Query;
import com.google.api.services.datastore.DatastoreV1.Filter;
import com.google.protobuf.ByteString;
import static com.google.api.services.datastore.client.DatastoreHelper.*;

import java.util.LinkedList;
import java.util.List;
import java.util.logging.Logger;

/**
 * Provide access to games entities in datastore.
 */
public class GameAccess extends DataStoreAccess {

    public static final String KIND = "Game";
    private static final String DEFAULT_GAME_NAME = "New Game";
    private static final int DEFAULT_NUM_PLAYERS = 2;
    private static final int DEFAULT_DURATION = 72;
    private static final Double DEFAULT_REGION_COST_PCT_INCREASE = 0.1;

    // define default bounding region
    // // 37.6021,-122.0758 - house
    private static final double NW_LAT = 37.7;
    private static final double NW_LNG = -122.1;
    private static final double SE_LAT = 37.5;
    private static final double SE_LNG = -121.9;

    private static final Logger LOG = Logger.getLogger(GameAccess.class.getName());


    /**
     * Get the specified game if it is in the database.
     * If not in the database, add a new record for it based on defaults.
     * @param gameId game identifier
     */
    public GameBean getGameById(Long gameId) {
        GameBean game = null;

        try {
            System.out.println("About to get game for " + gameId);
            Entity entity = getGameEntity(KIND, gameId);
            game = new GameBean(entity);
        }
        catch (DatastoreException exception) {
            fatalError(exception);
        }

        return game;
    }

    /**
     * @return a list of open games.
     */
    public List<GameBean> getOpenGames() {

        Query.Builder query = Query.newBuilder();
        LOG.info("About to get all open games.");
        /*
        Filter nwLatFilter =
                makeFilter("nwLatitude",
                        DatastoreV1.PropertyFilter.Operator.LESS_THAN, makeValue(nwLat + regionHeight))
                        .build();
        DatastoreV1.Filter seLatFilter =
                makeFilter("nwLatitude",
                        DatastoreV1.PropertyFilter.Operator.GREATER_THAN_OR_EQUAL, makeValue(seLat))
                        .build();
        */
        //query.setFilter(makeFilter(nwLatFilter, seLatFilter));
        query.addKindBuilder().setName(KIND);

        DatastoreV1.RunQueryRequest request = DatastoreV1.RunQueryRequest.newBuilder().setQuery(query).build();
        DatastoreV1.RunQueryResponse response;
        List<GameBean> list = new LinkedList<>();

        try {
            response = datastore.runQuery(request);

            List<DatastoreV1.EntityResult> results =
                    response.getBatch().getEntityResultList();

            for (DatastoreV1.EntityResult result : results) {
                Entity gameEntity = result.getEntity();
                GameBean regionBean = new GameBean(gameEntity);
                list.add(regionBean);
            }
        }
        catch (  DatastoreException e) {
            e.printStackTrace();
        }
        LOG.info("returning " + list.size() + " open games");
        return list;
    }

    /**
     * Add a new game with the specified settings.
     * @return the new game bean or null if it could not be added.
     */
    public GameBean addNewGame(String gameName, int numPlayers, int durationHrs, double regionPctIncrease, String notes,
                               Double nwLat, Double nwLong, Double seLat, Double seLong)
            throws DatastoreException {

        // The ID will be generated by the datastore
        Key.Builder key = Key.newBuilder().addPathElement(
                Key.PathElement.newBuilder().setKind(KIND)); //.setId(id));

        Entity gameEntity = createGameEntity(key, gameName, numPlayers, durationHrs, regionPctIncrease, notes,
                nwLat, nwLong, seLat, seLong);

        Long newId = insertEntity(gameEntity);
        return new GameBean(gameEntity, newId);
    }

    /** update the game in the datastore */
    public boolean updateGame(GameBean game) throws DatastoreException {

        return updateEntity(createGameEntity(game));
    }

    /**
     * Get the game entity, and if its not there create one.
     * If the game is there, we need to update it.
     */
    private Entity getGameEntity(String kind, Long id) throws DatastoreException {

        // Create an RPC request to get entities by key.
        LookupRequest.Builder lreq = LookupRequest.newBuilder();
        // Set the entity key with only one `path_element`: no parent.
        Key.Builder key = Key.newBuilder().addPathElement(
                Key.PathElement.newBuilder().setKind(kind).setId(id));
        lreq.addKey(key); // Add one key to the lookup request.

        // Set the transaction, so we get a consistent snapshot of the entity at the time the txn started.
        ByteString tx = createTransaction();
        lreq.getReadOptionsBuilder().setTransaction(tx);
        // Execute the RPC and get the response.
        LookupResponse lresp = datastore.lookup(lreq.build());

        CommitRequest.Builder creq = createCommitRequest();

        Entity entity;
        if (lresp.getFoundCount() > 0) {
            System.out.println("Found a game entity with id = " + id);
            entity = lresp.getFound(0).getEntity();
        } else {
            System.out.println("No game entity found for id = " + id + ". Adding one.");
            // If no entity was found, create a new one.

            List<Long> regions = new LinkedList<>();
            entity = createGameEntity(key, DEFAULT_GAME_NAME, DEFAULT_NUM_PLAYERS,
                    DEFAULT_DURATION, DEFAULT_REGION_COST_PCT_INCREASE, "",
                    NW_LAT, NW_LNG, SE_LAT, SE_LNG);
            // Insert the entity in the commit request mutation.
            creq.getMutationBuilder().addInsert(entity);
        }

        // Execute the Commit RPC synchronously and ignore the response.
        // Apply the insert mutation if the entity was not found and close
        // the transaction.
        datastore.commit(creq.build());
        return entity;
    }

    private Entity createGameEntity(GameBean game) {

        // Set the entity key with only one `path_element`: no parent.
        Key.Builder key = Key.newBuilder().addPathElement(
                Key.PathElement.newBuilder().setKind(KIND).setId(game.getGameId()));

        return createGameEntity(key, game.getGameName(), game.getNumPlayers(),
                game.getDuration(), game.getRegionCostPercentIncrease(), game.getNotes(),
                game.getNwLatitudeCoord(), game.getNwLongitudeCoord(),
                game.getSeLatitudeCoord(), game.getSeLongitudeCoord());
    }

    /** @return new User entity with specified info */
    private Entity createGameEntity(
            Key.Builder key, String gameName, int numPlayers, int durationHrs, double regionCostPctInc, String notes,
            double nwLat, double nwLng, double seLat, double seLng) {
        Entity entity;
        Entity.Builder entityBuilder = Entity.newBuilder();
        // Set the entity key.
        entityBuilder.setKey(key);
        // - a utf-8 string: `user name`
        entityBuilder.addProperty(Property.newBuilder()
                .setName("gameName")
                .setValue(Value.newBuilder().setStringValue(gameName)));

        entityBuilder.addProperty(Property.newBuilder()
                .setName("numPlayers")
                .setValue(Value.newBuilder().setIntegerValue(numPlayers)));

        entityBuilder.addProperty(Property.newBuilder()
                .setName("duration")
                .setValue(Value.newBuilder().setIntegerValue(durationHrs)));

        entityBuilder.addProperty(Property.newBuilder()
                .setName("regionCostPercentIncrease")
                .setValue(Value.newBuilder().setDoubleValue(regionCostPctInc)));

        //entityBuilder.addProperty(Property.newBuilder()
        //        .setName("region")
        //        .setValue(Value.newBuilder().setEntityValue(RegionAccess.createRegionEntity(region))));

        entityBuilder.addProperty(Property.newBuilder()
                .setName("nwLatitudeCoord")
                .setValue(Value.newBuilder().setDoubleValue(nwLat)));
        entityBuilder.addProperty(Property.newBuilder()
                .setName("nwLongitudeCoord")
                .setValue(Value.newBuilder().setDoubleValue(nwLng)));
        entityBuilder.addProperty(Property.newBuilder()
                .setName("seLatitudeCoord")
                .setValue(Value.newBuilder().setDoubleValue(seLat)));
        entityBuilder.addProperty(Property.newBuilder()
                .setName("seLongitudeCoord")
                .setValue(Value.newBuilder().setDoubleValue(seLng)));

        // Build the entity.
        entity = entityBuilder.build();
        return entity;
    }
}
